import { GIModel } from './GIModel';
import { TColor, TNormal, TTexture } from './GICommon';
import { TCoord } from './GIJSon';
/**
 * Export to obj
 */
export function exportObj(model: GIModel): string {
    const h_str = '# File generated by Mobius.\n';
    // the order of data is 1) vertex, 2) texture, 3) normal
    let v_str = '';
    let vt_str = '';
    let vn_str = '';
    let f_str = '';
    let l_str = '';
    // do we have color, texture, normal?
    const has_color_attrib: boolean = model.attribs().hasVertAttrib('color');
    const has_normal_attrib: boolean = model.attribs().hasVertAttrib('normal');
    const has_texture_attrib: boolean = model.attribs().hasVertAttrib('uv');
    // positions
    if (has_color_attrib) {
        for (let vert_i = 0; vert_i < model.geom().numVerts(); vert_i++) {
            const color: TColor = model.attribs().getVertAttribValueByIndex('color', vert_i) as TColor;
            const coord: TCoord = model.attribs().getVertCoordByIndex(vert_i);
            v_str += 'v ' + coord.map( v => v.toString() ).join(' ') + color.map( c => c.toString() ).join(' ') + '\n';
        }
    } else {
        for (let posi_i = 0; posi_i < model.geom().numPosis(); posi_i++) {
            const coord: TCoord = model.attribs().getPosiCoordByIndex(posi_i);
            v_str += 'v ' + coord.map( v => v.toString() ).join(' ') + '\n';
        }
    }
    // textures, vt
    if (has_texture_attrib) {
        for (let vert_i = 0; vert_i < model.geom().numVerts(); vert_i++) {
            const color: TColor = model.attribs().getVertAttribValueByIndex('normal', vert_i) as TColor;
            vt_str += 'v ' + color.map( v => v.toString() ).join(' ') + '\n';
        }
    }
    // normals, vn
    if (has_normal_attrib) {
        for (let vert_i = 0; vert_i < model.geom().numVerts(); vert_i++) {
            const color: TColor = model.attribs().getVertAttribValueByIndex('normal', vert_i) as TColor;
            vn_str += 'v ' + color.map( v => v.toString() ).join(' ') + '\n';
        }
    }
    // faces, f
    for (let pgon_i = 0; pgon_i < model.geom().numPgons(); pgon_i++) {
        const verts_i: number[][] = model.geom().navPgonToVert(pgon_i);
        const verts_i_outer = verts_i[0];
        if (has_texture_attrib) {
            // TODO
        }
        if (has_normal_attrib) {
            // TODO
        }
        if (has_color_attrib) {
            f_str += 'f ' + verts_i_outer.map( vert_i => (vert_i + 1).toString() ).join(' ') + '\n';
        } else {
            f_str += 'f ' + verts_i_outer.map( vert_i => (model.geom().navVertToPosi(vert_i) + 1).toString() ).join(' ') + '\n';
        }
    }
    // polygons
    return h_str + v_str + v_str + vt_str + vn_str + f_str + l_str;
}
