import { GIModel } from './GIModel';
import { TColor, TNormal, TTexture, EAttribNames, Txyz} from './common';
/**
 * Export to obj
 */
export function exportObj(model: GIModel): string {
    const h_str = '# File generated by Mobius.\n';
    // the order of data is 1) vertex, 2) texture, 3) normal
    let v_str = '';
    let vt_str = '';
    let vn_str = '';
    let f_str = '';
    let l_str = '';
    // do we have color, texture, normal?
    const has_color_attrib: boolean = model.attribs.query.hasVertAttrib(EAttribNames.COLOR);
    const has_normal_attrib: boolean = model.attribs.query.hasVertAttrib(EAttribNames.NORMAL);
    const has_texture_attrib: boolean = model.attribs.query.hasVertAttrib(EAttribNames.TEXTURE);
    // positions
    if (has_color_attrib) {
        for (let vert_i = 0; vert_i < model.geom.query.numVerts(); vert_i++) {
            const color: TColor = model.attribs.query.getVertAttribValueByIndex(EAttribNames.COLOR, vert_i) as TColor;
            const coord: Txyz = model.attribs.query.getVerTxyzByIndex(vert_i);
            v_str += 'v ' + coord.map( v => v.toString() ).join(' ') + color.map( c => c.toString() ).join(' ') + '\n';
        }
    } else {
        for (let posi_i = 0; posi_i < model.geom.query.numPosis(); posi_i++) {
            const coord: Txyz = model.attribs.query.getPosiCoordByIndex(posi_i);
            v_str += 'v ' + coord.map( v => v.toString() ).join(' ') + '\n';
        }
    }
    // textures, vt
    if (has_texture_attrib) {
        for (let vert_i = 0; vert_i < model.geom.query.numVerts(); vert_i++) {
            const texture: TTexture = model.attribs.query.getVertAttribValueByIndex(EAttribNames.TEXTURE, vert_i) as TTexture;
            vt_str += 'v ' + texture.map( v => v.toString() ).join(' ') + '\n';
        }
    }
    // normals, vn
    if (has_normal_attrib) {
        for (let vert_i = 0; vert_i < model.geom.query.numVerts(); vert_i++) {
            const normal: TNormal = model.attribs.query.getVertAttribValueByIndex(EAttribNames.NORMAL, vert_i) as TNormal;
            vn_str += 'v ' + normal.map( v => v.toString() ).join(' ') + '\n';
        }
    }
    // faces, f
    for (let pgon_i = 0; pgon_i < model.geom.query.numPgons(); pgon_i++) {
        const verts_i: number[][] = model.geom.query.navPgonToVert(pgon_i);
        const verts_i_outer = verts_i[0];
        if (has_texture_attrib) {
            // TODO
        }
        if (has_normal_attrib) {
            // TODO
        }
        if (has_color_attrib) {
            f_str += 'f ' + verts_i_outer.map( vert_i => (vert_i + 1).toString() ).join(' ') + '\n';
        } else {
            f_str += 'f ' + verts_i_outer.map( vert_i => (model.geom.query.navVertToPosi(vert_i) + 1).toString() ).join(' ') + '\n';
        }
    }
    // polygons
    return h_str + v_str + v_str + vt_str + vn_str + f_str + l_str;
}
