import * as Mathjs from 'mathjs';

export const boolean = Mathjs.boolean;
export const number = Mathjs.number;
export const string = Mathjs.string;
export const mad = Mathjs.mad;
export const mean = Mathjs.mean;
export const median = Mathjs.median;
export const mode = Mathjs.mode;
export const prod = Mathjs.prod;
export const std = Mathjs.std;
export const vari = Mathjs.var;
export const sum = Mathjs.sum;
export const hypot = Mathjs.hypot;
export const norm = Mathjs.norm;
export const mod = Mathjs.mod;
export const square = Mathjs.square;
export const cube = Mathjs.cube;
export const distance = Mathjs.distance;
export const random = Mathjs.random;
export const randomInt = Mathjs.randomInt;
export const pickRandom = Mathjs.pickRandom;
